config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)' do
    devise_for :users, skip: :omniauth_callbacks
    resources :images, only: %i[index show new create] do
      get :download, on: :member

      resources :comments, only: %i[new create]
    end

    resources :categories do
      put :follow, on: :member
      put :unfollow, on: :member
    end

    resources :hearts, only: %i[create destroy]
    get 'comments', to: 'comments#index'
    root to: 'dashboard#index'
  end
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :image, counter_cache: :hearts_count
  belongs_to :user

  validates :user_id, uniqueness: { scope: :image_id }
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController

  def create
    @user = current_user
    @image = Image.find(params[:id])
    @user.heart!(@image)
    record_activity('create heart')
  end

  def destroy
    @user = current_user
    @heart = @user.hearts.find_by_image_id(params[:id])
    @image = Image.find(params[:id])
    @heart.destroy!
  end
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/views/hearts/_button.html.haml
- if current_user.heart?(@image)
  =link_to heart_path(id: @image.id), method: 'delete', remote: true do
    %i.fas.fa-heart
- else
  =link_to hearts_path(id: @image.id), method: :post, remote: true do
    %i.far.fa-heart

app/views/hearts/create.js.erb
$('#heart-button').html('<%= j link_to("<i class=\"fas fa-heart\"></i>".html_safe, heart_path(id: @image.id), method: :delete, remote: true) %>')
$("#heart-count").html('<%= @image.reload.hearts_count %>')

app/views/hearts/destroy.js.erb
$('#heart-button').html('<%= j link_to("<i class=\"far fa-heart\"></i>".html_safe, hearts_path(id: @image.id), method: :post, remote: true) %>')
$("#heart-count").html('<%= @image.reload.hearts_count %>')