config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)' do
    devise_for :users, skip: :omniauth_callbacks
    resources :images, only: %i[index show new create] do
      get :download, on: :member

      resources :comments, only: %i[new create]
    end

    resources :categories do
      put :follow, on: :member
      put :unfollow, on: :member
    end

    resources :hearts, only: %i[create destroy]
    get 'comments', to: 'comments#index'
    root to: 'dashboard#index'
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  extend FriendlyId

  has_many :images, dependent: :destroy
  belongs_to :user

  validates :title, presence: true

  friendly_id :title, use: :slugged

  acts_as_followable

  paginates_per 12

  scope :newest, -> { order(created_at: :desc2) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_category, only: %i[show destroy follow unfollow]

  def index
    @categories = Category.all.order(images_count: :desc).page(params[:page])
    record_activity('navigation')
  end

  def show
    @images = @category.images.page(params[:page]).per 12
    record_activity('navigation')
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(categories_params)

    if @category.save
      record_activity('create category')
      flash[:notice] = 'Category created'
      redirect_to categories_path
    else
      flash[:alert] = 'Category was not create, try again'
      render 'new'
    end
  end

  def destroy
    @category.destroy
    record_activity('delete category')
    flash[:alert] = 'Category and images removed'
    redirect_to categories_path
  end

  def follow
    current_user.follow(@category)
    @follow = Follow.find_by(follower: current_user, followable: @category)
    FollowEmail.perform([current_user.id, @category.title])
    record_activity('follow category')
  end

  def unfollow
    current_user.stop_following(@category)
    record_activity('unfollow category')
  end

  private

  def categories_params
    params.require(:category).permit(:title)
  end

  def find_category
    @category = Category.friendly.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def top_5_categories
    Category.all.each do |category|
      top_img_counter = 0
      category.images.each { |i| top_img_counter += (i.hearts_count + i.comments_count) }
      category.range_counter = category.images_count + top_img_counter
      category.save!
    end
    Category.all.order(range_counter: :desc).limit(5)
  end
end

app/views/categories/_following_button.html.haml
#follow-button.d-inline
  -if current_user.following?(category)
    =button_to (t('categories.index.unfollow')), unfollow_category_path(id: category.slug), method: 'put', class: 'btn btn-outline-primary', remote: true
  -else
    =button_to (t('categories.index.follow')), {action: 'follow'}, method: 'put', class: 'btn btn-outline-primary', remote: true

app/views/categories/_form.html.haml
.section
  = form_for @category, url: { action: 'create' }  do |f|
    .field
      = f.label :title
      = f.text_field :title
    = f.submit t('activerecord.attributes.category.create'), class: 'btn btn-secondary'

app/views/categories/_modal_new.html.haml
#categoryModal.modal.fade{:role => "dialog"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Create a new Category
      .modal-body
        = form_for Category.new, :html => { :multipart => true } do |f|
          .field
            = f.label :title
            = f.text_field :title, placeholder: 'Category Name'
            = f.submit t('activerecord.attributes.category.create'), class: 'btn btn-secondary'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/categories/follow.js.erb
$('#follow-button').html('<%= j button_to(t('categories.index.unfollow'), unfollow_category_path(id: @category.slug), method: :put, class: 'btn btn-outline-primary', remote: true) %>')

app/views/categories/index.html.haml
%h2
  .title
    = t('categories.index.categories')
- if @categories.exists?
  - @categories.each_slice(4) do |category|
    %div
      .row
        - category.each do |category|
          .col-mid-3
            .photo2.photo-type-line2
              %a.photo-hover2{ "data-title" => category.title, :href => category_path(category) }
                .photo-info2
                  .headline2= category.title
                  .line2
                  .desc2
                    = "Rating:"
                    = category.range_counter
                  .mask
                .photo-img
                  - if category.images.first.present?
                    = image_tag category.images.first.picture.thumb.url
                  - else
                    = image_tag 'background.jpg', style: "width: 275px; height: 220px"
- else
  %p
    = t('categories.index.no_categories')
#paginate
  = paginate @categories

app/views/categories/new.html.haml
- content_for :page_title, "Create a new Category"
= render 'form'

app/views/categories/show.html.haml
#gallery
  %h2
    #{Category.friendly.find(params[:id]).title}

  - if @images.exists?
    - @images.each_slice(4) do |image|
      %div
        .row
          - image.each do |image|
            .col-mid-3
              .photo2.photo-type-line2
                %a.photo-hover2{"data-title" => image.name, :href => image_path(image)}
                  .photo-info2
                    .headline2= image.name
                    .line2
                    .desc2= image.category.title
                    .mask
                  .photo-img
                    = image_tag image.picture.thumb.url
  - else
    %p.title
      = t('images.index.no_images')

  .buttons
    = render 'categories/following_button', category: @category

    -if @category.user.eql?(current_user)
      = button_to (t('categories.index.delete_category')), {action: 'destroy'}, data: { confirm: t('categories.index.delete_category.confirm')}, method: :delete, class: 'btn btn-danger', remote: true
#paginate
  =paginate @images

app/views/categories/unfollow.js.erb
$('#follow-button').html('<%= j button_to(t('categories.index.follow'), follow_category_path(id: @category.slug), method: :put, class: 'btn btn-outline-primary', remote: true) %>')