config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)' do
    devise_for :users, skip: :omniauth_callbacks
    resources :images, only: %i[index show new create] do
      get :download, on: :member

      resources :comments, only: %i[new create]
    end

    resources :categories do
      put :follow, on: :member
      put :unfollow, on: :member
    end

    resources :hearts, only: %i[create destroy]
    get 'comments', to: 'comments#index'
    root to: 'dashboard#index'
  end
end

app/models/image.rb
class Image < ApplicationRecord
  extend FriendlyId

  belongs_to :category, counter_cache: :images_count
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :hearts, dependent: :destroy

  validates :name, presence: true
  validates :picture, presence: true, file_size: { less_than: 50.megabytes }

  friendly_id :name, use: :slugged

  mount_uploader :picture, PictureUploader

  paginates_per 16
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  respond_to :html, :js

  before_action :set_image, only: %i[show edit download]

  def new
    @image = Image.new
  end

  def index
    @images = Image.order(hearts_count: :desc).page(params[:page])
    # record_activity('navigation')
  end

  def show
    @comments = Comment.where(image_id: @image).order('created_at DESC')
    record_activity('navigation')
  end

  def create
    @image = current_user.images.build(image_params)

    if @image.save
      record_activity('create image')
      UserMailer.with(user: current_user, category: params[:id]).new_image_email.deliver_now
      flash[:notice] = 'Image Uploaded'
      redirect_to image_path(@image)
    else
      flash[:alert] = 'Image not save'
      render 'new'
    end
  end

  def edit
  end

  def download
    send_data(open(@image.picture.url).read, filename: File.basename(@image.picture.path))
  end

  private

  def set_image
    @image = Image.friendly.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:name, :category_id, :picture)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.haml
.upload_form
  = form_for @image, :html => {:multipart => true}  do |f|
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :picture
      = f.file_field :picture
    .field
      = f.label :category
      = f.select :category_id, Category.all.collect { |x| [x.title, x.id] }, { :include_blank => t('activerecord.attributes.image.select_category') },class:'form-control'
    = f.submit t('activerecord.attributes.image.create'), class: 'btn btn-secondary'

app/views/images/_modal.html.haml
#imageModal.modal.fade{:role => "dialog"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Create a new Image
      .modal-body
        = form_for Image.new, :html => {:multipart => true}  do |f|
          .field
            = f.label :name
            = f.text_field :name, placeholder: 'Image Name'
          .field
            = f.label :picture
            = f.file_field :picture
          .field
            = f.label :category
            = f.select :category_id, Category.all.collect { |x| [x.title, x.id] }, { :include_blank => t('activerecord.attributes.image.select_category') },class:'form-control'
          = f.submit t('activerecord.attributes.image.create'), class: 'btn btn-secondary'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/images/edit.html.haml
- content_for :page_title, "Edit Image"
= render 'form'

app/views/images/index.html.haml
#gallery
  %h2
    .title
      = t('.show')
  - if @images.exists?
    .row
      - @images.each do |image|
        .col-md-3-expand-xl.column
          .photo.photo-type-line
            %a.photo-hover{:href => image_path(image)}
              .photo-info
                .headline= image.name
                .line
                .desc= image.category.title
                .mask{ onmouseover: 'mouseIn(this);',
                       onmouseout: 'mouseOut(this);' }
              .photo-img
                = image_tag image.picture.thumb.url, class: 'img-list'
  - else
    %p
      .title
        = t('.no_images')
#paginate
  = paginate @images

app/views/images/new.html.haml
- content_for :page_title, "Create a new image"
= render 'form'

app/views/images/show.html.haml
%h2
  = @image.name
%br
  .image
    = image_tag(@image.picture.large.url, alt: 'some_image')
%br
%div
  #heart-button.d-inline
    = render 'hearts/button'
  #heart-count.d-inline
    = @image.hearts_count
  -if user_signed_in?
    #comment-form.d-inline
      =link_to new_image_comment_path(image_id: @image.slug), remote: true do
        %i.fas.fa-comment-dots
          %i.comments_counter
            = @image.comments_count
  =link_to download_image_path(id: @image.id), target: '_blank' do
    %i.fas.fa-download

  #comments-container
    %ul#comments
    .image_comments
      %a.toggleLink{:href => "#", 'data-remote' => 'true', } See all Comments
      %i.comments
        -if @comments.load.any?
          %i.comment_title
            ="Comments : "
          -@comments.each do |comment|
            .commentlistitem
              %ul
                %li
                  =comment.body
                %i.title
                  ="Commented by:"
                =comment.user.email
                %br
                %i.title
                  =comment.created_at.strftime('%H:%M:%S')
                %br
                %i.title
                  =comment.created_at.strftime('%v')
        -else
          %i.title
            ='No comments yet'