config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)' do
    devise_for :users, skip: :omniauth_callbacks
    resources :images, only: %i[index show new create] do
      get :download, on: :member

      resources :comments, only: %i[new create]
    end

    resources :categories do
      put :follow, on: :member
      put :unfollow, on: :member
    end

    resources :hearts, only: %i[create destroy]
    get 'comments', to: 'comments#index'
    root to: 'dashboard#index'
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :action, :url, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  extend FriendlyId

  has_many :images, dependent: :destroy
  belongs_to :user

  validates :title, presence: true

  friendly_id :title, use: :slugged

  acts_as_followable

  paginates_per 12

  scope :newest, -> { order(created_at: :desc2) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image, counter_cache: :comments_count

  validates :body, presence: true
  validates :user, presence: true

  paginates_per 5
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true, counter_cache: :follows_count
  belongs_to :follower,   polymorphic: true

  paginates_per 5

  def block!
    self.update_attribute(:blocked, true)
  end
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :image, counter_cache: :hearts_count
  belongs_to :user

  validates :user_id, uniqueness: { scope: :image_id }
end

app/models/image.rb
class Image < ApplicationRecord
  extend FriendlyId

  belongs_to :category, counter_cache: :images_count
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :hearts, dependent: :destroy

  validates :name, presence: true
  validates :picture, presence: true, file_size: { less_than: 50.megabytes }

  friendly_id :name, use: :slugged

  mount_uploader :picture, PictureUploader

  paginates_per 16
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and
  devise :database_authenticatable, :registerable, :recoverable,
         :confirmable, :rememberable, :validatable, :omniauthable,
         :lockable, :trackable, omniauth_providers: [:facebook]

  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :hearts, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :activities, dependent: :destroy

  acts_as_follower

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def heart!(image)
    self.hearts.create(image_id: image.id)
  end

  def unheart!(image)
    heart = self.hearts.find_by(image_id: image.id)
    heart.destroy!
  end

  def heart?(image)
    self.hearts.find_by_image_id(image.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_image, only: %i[new create]

  def index
    @comments = Comment.order(created_at: :desc).page(params[:page])
    record_activity('navigation')
  end

  def new
    @comment = @image.comments.new
  end

  def create
    @image.comments.create(comment_params.merge(user: current_user))
    record_activity('create comment')
    redirect_to image_path(@image)
  end

  private

  def find_image
    @image = Image.friendly.find(params[:image_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :image_id)
  end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController

  def create
    @user = current_user
    @image = Image.find(params[:id])
    @user.heart!(@image)
    record_activity('create heart')
  end

  def destroy
    @user = current_user
    @heart = @user.hearts.find_by_image_id(params[:id])
    @image = Image.find(params[:id])
    @heart.destroy!
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  respond_to :html, :js

  before_action :set_image, only: %i[show edit download]

  def new
    @image = Image.new
  end

  def index
    @images = Image.order(hearts_count: :desc).page(params[:page])
    # record_activity('navigation')
  end

  def show
    @comments = Comment.where(image_id: @image).order('created_at DESC')
    record_activity('navigation')
  end

  def create
    @image = current_user.images.build(image_params)

    if @image.save
      record_activity('create image')
      UserMailer.with(user: current_user, category: params[:id]).new_image_email.deliver_now
      flash[:notice] = 'Image Uploaded'
      redirect_to image_path(@image)
    else
      flash[:alert] = 'Image not save'
      render 'new'
    end
  end

  def edit
  end

  def download
    send_data(open(@image.picture.url).read, filename: File.basename(@image.picture.path))
  end

  private

  def set_image
    @image = Image.friendly.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:name, :category_id, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :js
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def top_5_categories
    Category.all.each do |category|
      top_img_counter = 0
      category.images.each { |i| top_img_counter += (i.hearts_count + i.comments_count) }
      category.range_counter = category.images_count + top_img_counter
      category.save!
    end
    Category.all.order(range_counter: :desc).limit(5)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/nokogiri/_form.html.haml
=semantic_form_for :nokogiri, builder: ActiveAdmin::FormBuilder, url: { action: :grab } do |f|
  =f.inputs do
    =f.input :url, label: false, placeholder: 'Paste your URL', input_html: { style: 'width: 50%;' }
    =f.action :submit, label: 'Get Images'

app/views/admin/nokogiri/_images.html.haml
- @images.each do |image|
  %p
    =image_tag(image[:src])

app/views/layouts/_footer.html.haml
%footer.navbar-inverse
  © Company 2018

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}

  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title
      =t('layouts.application.title')
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans", :rel => "stylesheet"}/
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.5.0/css/all.css", :integrity => "sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body

    .slider
      .content
        =image_tag('slider1.jpg', class: 'w-100 mySlides')
        =image_tag('slider2.jpg', class: 'w-100 mySlides')
        =image_tag('slider3.jpg', class: 'w-100 mySlides')
        =image_tag('slider4.jpg', class: 'w-100 mySlides')
      %i.display-left{onclick: "plusDivs(-1)"}
        =image_tag('left.png', class: 'left')
      %i.display-right{onclick: "plusDivs(1)"}
        =image_tag('right.png', class: 'right')

    .logo-navbar-container
      %i.fab.fa-instagram
      %i.nav-title
        = 'PhotoGallery'

    %nav.navbar.navbar-expand-xl
      %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
          %i.fas.fa-align-justify
      #navbarsExampleDefault.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            = link_to (t('layouts.application.home')), root_path, class: "nav-link"
            %a.nav-link{:href => "#"}
              %span.sr-only (current)
          %li.nav-item.dropdown.active
            %a#dropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "https://example.com"}
              = t('layouts.application.top_categories')
            .dropdown-menu{"aria-labelledby" => "dropdown"}
              - top_5_categories.each do |category|
                %a.dropdown-item{:href => "#{category_path(category)}"}
                  = category.title
          %li.nav-item.active
            = link_to (t('layouts.application.images')), images_path, class: "nav-link"
          %li.nav-item.active
            = link_to (t('layouts.application.comments')), comments_path, class:"nav-link"
          %li.nav-item.dropdown.active
            %a#dropdown02.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "https://example.com"}
              = t('layouts.application.account')
            .dropdown-menu{"aria-labelledby" => "dropdown02"}
              - if user_signed_in?
                = link_to (t('layouts.application.logout')), destroy_user_session_path, class: "dropdown-item alert-danger", method: :delete
              - else
                = link_to (t('layouts.application.login')), new_user_session_path, class: "dropdown-item"
              = link_to (t('layouts.application.edit_profile')), edit_user_registration_path, class: "dropdown-item alert-info"
          %li.nav-item.active
            = link_to (t('layouts.application.categories')), categories_path, class:"nav-link"
        %ul.nav.navbar-nav.pull-right
          %li.nav-item.active
            = link_to(t('layouts.application.upload_images'), '#imageModal', 'data-toggle' => 'modal', class: 'nav-link')
          %li.nav-item.active
            = link_to(t('layouts.application.add_category'), '#categoryModal', 'data-toggle' => 'modal', class: 'nav-link')

          %li.nav-item.active
            %i.fas.fa-globe-americas
          %li.nav-item.active
            -if I18n.locale == :ru
              =link_to('En', { locale: :en }, class: 'nav-link')
            -else
              =link_to('Ru', { locale: :ru }, class: 'nav-link')

    .container-fluid
      - if flash[:notice]
        .alert.alert-success= flash[:notice]
      - if flash[:alert]
        .alert.alert-danger= flash[:alert]
      = render 'images/modal'
      = render 'categories/modal_new'
      = yield
    -#= render 'layouts/footer'

    -if controller_name == 'dashboard'
      .images-container
        - if @images.exists?
          .row2
            - @images.each do |image|
              .col-md-2-expand-xl
                .photo2.photo-type-line2
                  .photo-hover2
                    .photo-info2
                      .headline2= image.name
                      .line2
                      .desc2= image.category.title
                      .mask2
                    .photo-img2
                      = image_tag image.picture.thumb.url, class: 'images_list_dashboard'

    .footer